/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: 7784c6d8-1548-4f08-aa02-25c9229cb955
*/

package com.forecast.weather.service.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.lang.UnsupportedOperationException;
import java.util.stream.Stream;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import com.forecast.weather.model.WeatherInfo;

@DisplayName("Testing Method getWeatherInformation")
@SuppressWarnings("unused")
public class WeatherForecastServiceImplGetWeatherInformationTest {

//region Factories
	private static WeatherForecastServiceImpl createWeatherForecastService() {
		// TODO: implement factory
		throw new UnsupportedOperationException("Please implement Factory Method");
	}
//endregion

//region Test methods
	@DisplayName("getWeatherInformation")
	@ParameterizedTest(name = "{0} [{index}] expected: ''{3}'' input: ''{1}'', ''{2}''")
	@MethodSource({"ExpectedReturnValueTests"})
	public void getWeatherInformationTest(String testDescription, WeatherForecastServiceImpl instance, Integer zipcode, WeatherInfo expected) {
		WeatherInfo actual = instance.getWeatherInformation(zipcode);
		assertEquals(expected, actual);
	}
//endregion

//region Test data
	private static Stream<Arguments> ExpectedReturnValueTests() {
		return Stream.of(
			Arguments.of(
				/* String testDescription = */ "p1:",
				/* WeatherForecastServiceImpl instance = */ createWeatherForecastService(),
				/* Integer zipcode = */ 123456,
				/* WeatherInfo expectedValue = */ null
			),
			Arguments.of(
				/* String testDescription = */ "n1: instance: invalid:",
				/* WeatherForecastServiceImpl instance = */ null,
				/* Integer zipcode = */ 123456,
				/* WeatherInfo expectedValue = */ null
			),
			Arguments.of(
				/* String testDescription = */ "n2: zipcode: invalid:",
				/* WeatherForecastServiceImpl instance = */ createWeatherForecastService(),
				/* Integer zipcode = */ 123,
				/* WeatherInfo expectedValue = */ null
			)
		);
	}
//endregion

}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAA/81UUW/aMBB+Bon/cMoLKaJJodBSuk2tBu14oFSDrZqmPbjOQd0lTmY7tBTx32cngYUVUNe+7CU5n+8
733ff2W6lVKxAZwBXgxH0B53exTcYfeoN4eOg3+9ejczuJXIURKEHtzPwcBpo2/hHKBUEoYd+G46PWw165LX2a81Ga7
8xPmjtE3JQ36836Um9fkJvT5pNjXFLxVIxIvQnmSDQMHDGoUBKpHIekKg7FI5EMWUUHRZE/qmJ1kYoFEhFFKMQiolzH
3Om9DdiSgNIxJxzqWGKhVw6JDG7v2Liyzz+nkyJ4xM+cb5wGUfGh94gMsQ0rvtIMTLG6TogVsx3pBJIAmeY/PI5NxfT
YTLyyeyKBHi6IzQiggTSuTY/1A72hJ7p6AswkQinzNPrczGJA+RK/guoj+ou9IZhLCjm2WyUI5HXuUlXPT4OE8RZjqN
tmaoZn0CaGCaocvEiSBps7WnUUPddoJQ3RHANkLYV81iiZzaj+NbX+lJfCwgZ/iKrZpjORE+PxOWm5Mkgzk1hritwoj
1wQagKBUNZKhYiwaZ6ZJcjtD05UK2wws0B9p45olBwXRgNOoM2mAlF030YJ4fNzK66E+EDcHyAnWNmW9c+Eom5JGnFs
6yL1p5udGFhGCH3UlJrBNPLl8QajuuKbJWgcPZs3myu1/AerPnBAr7PGffwcfED8DFCqmtvQ7k8P1yUy8B4FKtkWdPL
qjHq2kjT5ofKnlvdDP0ZVSz4V+LHaM6S1sJEZ1pPQ7ZlWpK69H0zU6W03UFJBUs6V92lH+NaY06xCj2ucIICnlhE9Qi
vUOaQFbdM0fyWFkG/HLody1TOxgLtLG+iUiH/5tjL5NUs14uE9Igizyc1fXHerW75B9jW1+VwisSfAZ1wbBtnYZVg5S
m4FdjcX0294oIV1dpWdRX6gpanuN0X6E/Cv+RJwbX6YaN59OzUNckSymk4j30/ic3yvoIlr7VXBIw1JT7zXkXcFPP/0
au3lyW8jd1bZX0FafPdcnW05zfJFhVqtwgAAA==
END_CODEGEN_DATA
*/
